language: python
python:
- 3.5.1
services:
- postgresql
env:
- DJANGO=1.9.5
before_install:
- export DJANGO_SETTINGS_MODULE=WhiskeyProof.travis-settings
- export PYTHONPATH=$HOME/builds/Aaron/WhiskeyProof
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE whiskey_proof;" -U postgres
- python manage.py migrate
script:
- coverage run --source='.' manage.py test whiskies
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: TPc86AVahQkLO1YveQpuU7fs/3WGHqRKsfozTa3Mu9P1iHnYCYLTQssCc+Ygnw4Na8BFJfA6POB04ZcDa7EMdBbimqooz4DaYT88mxNu32jyQYjm5DZi4rvK0cNqW5+nN+AjCDJ/lW0CPjgF6QWjtyHWuoXWuXlrNVG47QmxkzX/Eh7nGS4PK+/T5gJeLBd1OKb2/mgV52X+m6GyjEr+l3yemTPaCY2pRKOaPSHoxpBrfqwvDQPzd3mYT8ujT9E98vZbsfcj9yiKkv7TpetXgo3j5hdIf4o4oDHf+RWOpMI7uziluuglLC/iRP9XQN4K7++UEW76Q1H54yR4JMnDqWuOPZd+rNuVRQmoj+dbWLKhidzwruV+ixjRr3HJDJYm9CzXeb+4abURvCaRU09L+jCfFMBAZtneLWZlNWejqBpWpmVrB1B8PFerEN5I5qnihpw8gy4smXP4z1f1tLxph+I8rRItoTafDnMnRlUY8RUY/UNqYL5wmdO9NnstHmLUAfB95fZAwpj0vOHfCz/wsJ4+QDpCY1mahVRjRh6mPQPK/rSuWspoGL/g1rN6FeQ8ck77/GkFTlHWpCctWMYzdR6bv2d070ZI3dkSX4Gw09CU/ZxaqQ3aUU1KSyrsUzYi5Hpq+v/GqRLUwZ3oxZo0pvqaHQNHs8WY/kASllpBBaw=
  app: evening-citadel-85778
  on:
    repo: WhiskeyProject/whiskey-api
